### PR TITLE
Issue37 - Use redirect function rather than instantiating redirect response instances.

### PR DESCRIPTION
**Pull request by jvzammit**
Run tests:
```
fab test
```

Also upgraded Django version to Django 1.6.11, i.e. latest 1.6 version.

### CODE REVIEW

**Comment by ivancrneto** [comment]
we are not using Django 1.6 yet, why are you updating Django requirement here?

**Comment by ivancrneto** [comment]
why are we dropping support to django 1.5? this change in requirements will force everything that uses urlographer to upgrade to django 1.6

**Comment by jvzammit** [comment]
@ivancrneto You're right, will remove that commit from this PR. Thanks.

**Comment by jvzammit** [comment]
@ivancrneto Removed commit that changed Django version. Thanks.

**Comment by ivancrneto** [comment]
@jvzammit can you make sure the tests pass?

**Comment by jvzammit** [comment]
Closing as this is a minor change that perhaps not worth reviewing/merging at the moment. @ivancrneto thanks.

**Pull request closed without merging**
